version: '3.4'

services:
  hellodocker-console-1:
    image: saurabhacidemo2.azurecr.io/hellodockerconsole:latest
    build:
      context: .
      dockerfile: HelloDocker.Console/Dockerfile
    environment:
      - CLIENT_ID=YY9663
      - DB_CONN=Server=algo-db-server.database.windows.net,1433;Database=algo-db;User ID=algo_user;Password=$$Pr0f!7@2022@!#;MultipleActiveResultSets=true;

  hellodocker-console-2:
    image: saurabhacidemo2.azurecr.io/hellodockerconsole:latest
    build:
      context: .
      dockerfile: HelloDocker.Console/Dockerfile
    environment:
      - CLIENT_ID=ABCDEF
      - DB_CONN=Server=algo-db-server.database.windows.net,1433;Database=algo-db;User ID=algo_user;Password=$$Pr0f!7@2022@!#;MultipleActiveResultSets=true;


